In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('spotify_churn_dataset.csv')
df

user_id  gender  age country subscription_type  listening_time  \
0           1  Female   54      CA              Free              26   
1           2   Other   33      DE            Family             141   
2           3    Male   38      AU           Premium             199   
3           4  Female   22      CA           Student              36   
4           5   Other   29      US            Family             250   
...       ...     ...  ...     ...               ...             ...   
7995     7996   Other   44      DE           Student             237   
7996     7997    Male   34      AU           Premium              61   
7997     7998  Female   17      US              Free              81   
7998     7999  Female   34      IN           Student             245   
7999     8000   Other   45      AU              Free             210   

      songs_played_per_day  skip_rate device_type  ads_listened_per_week  \
0                       23       0.20     Desktop                     31   
1                       62       0.34         Web                      0   
2                       38       0.04      Mobile                      0   
3                        2       0.31      Mobile                      0   
4                       57       0.36      Mobile                      0   
...                    ...        ...         ...                    ...   
7995                    36       0.30      Mobile                      0   
7996                    64       0.59      Mobile                      0   
7997                    62       0.33     Desktop                      5   
7998                    94       0.27     Desktop                      0   
7999                    68       0.46     Desktop                      6   

      offline_listening  is_churned  
0                     0           1  
1                     1           0  
2                     1           1  
3                     1           0  
4                     1           1  
...                 ...         ...  
7995                  1           1  
7996                  1           0  
7997                  0           0  
7998                  1           0  
7999                  0           0  

[8000 rows x 12 columns]

In [3]:
df.dtypes

user_id                    int64
gender                    object
age                        int64
country                   object
subscription_type         object
listening_time             int64
songs_played_per_day       int64
skip_rate                float64
device_type               object
ads_listened_per_week      int64
offline_listening          int64
is_churned                 int64
dtype: object

In [4]:
df.drop(['user_id'],axis=1,inplace=True)

In [5]:
from sklearn.preprocessing import LabelEncoder
lab=LabelEncoder()
df['gender']=lab.fit_transform(df['gender'])
df['country']=lab.fit_transform(df['country'])
df['subscription_type']=lab.fit_transform(df['subscription_type'])
df['device_type']=lab.fit_transform(df['device_type'])


In [6]:
x=df.iloc[:,:-1].values
x

array([[ 0., 54.,  1., ...,  0., 31.,  0.],
       [ 2., 33.,  2., ...,  2.,  0.,  1.],
       [ 1., 38.,  0., ...,  1.,  0.,  1.],
       ...,
       [ 0., 17.,  7., ...,  0.,  5.,  0.],
       [ 0., 34.,  4., ...,  0.,  0.,  1.],
       [ 2., 45.,  0., ...,  0.,  6.,  0.]], shape=(8000, 10))

In [7]:
y=df.iloc[:,-1].values
y

array([1, 0, 1, ..., 0, 0, 0], shape=(8000,))

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=1)
x_train

array([[ 0., 23.,  2., ...,  0.,  0.,  1.],
       [ 0., 57.,  5., ...,  0.,  0.,  1.],
       [ 0., 47.,  0., ...,  1.,  0.,  1.],
       ...,
       [ 1., 42.,  0., ...,  1.,  0.,  1.],
       [ 0., 22.,  6., ...,  0.,  0.,  1.],
       [ 0., 35.,  0., ...,  2., 35.,  0.]], shape=(5600, 10))

In [9]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [10]:
from sklearn.naive_bayes import BernoulliNB
model=BernoulliNB()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0], shape=(2400,))

In [11]:
y_test

array([0, 0, 0, ..., 0, 1, 0], shape=(2400,))

In [12]:
from sklearn.metrics import accuracy_score

score=accuracy_score(y_test,y_pred)
score

0.7445833333333334

In [13]:
from sklearn.metrics import classification_report
report=classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.74      1.00      0.85      1787
           1       0.00      0.00      0.00       613

    accuracy                           0.74      2400
   macro avg       0.37      0.50      0.43      2400
weighted avg       0.55      0.74      0.64      2400



c:\Users\aswat\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\aswat\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\aswat\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(ave