In [7]:
outlook =     ["Sunny", "Sunny", "Overcast", "Rain", "Rain", "Rain", "Overcast",
               "Sunny", "Sunny", "Rain", "Sunny", "Overcast", "Overcast", "Rain"]
temperature = ["Hot", "Hot", "Hot", "Mild", "Cool", "Cool", "Cool",
               "Mild", "Cool", "Mild", "Mild", "Mild", "Hot", "Mild"]
humidity =    ["High", "High", "High", "High", "Normal", "Normal", "Normal",
               "High", "Normal", "Normal", "Normal", "High", "Normal", "High"]
wind =        ["Weak", "Strong", "Weak", "Weak", "Weak", "Strong", "Strong",
                "Weak", "Weak", "Weak", "Strong", "Strong", "Weak", "Strong"]
decision =    ["No", "No", "Yes", "Yes", "Yes", "No", "Yes",
               "No", "Yes", "Yes", "Yes", "Yes", "Yes", "No"]


In [8]:
#Encoding
from sklearn.preprocessing import LabelEncoder
lab=LabelEncoder()
outlook_encoder=lab.fit_transform(outlook)
outlook_encoder

array([2, 2, 0, 1, 1, 1, 0, 2, 2, 1, 2, 0, 0, 1])

In [9]:
from sklearn.preprocessing import LabelEncoder
lab=LabelEncoder()
temperature_encoder=lab.fit_transform(temperature)
temperature_encoder

array([1, 1, 1, 2, 0, 0, 0, 2, 0, 2, 2, 2, 1, 2])

In [10]:
from sklearn.preprocessing import LabelEncoder
lab=LabelEncoder()
humidity_encoder=lab.fit_transform(humidity)
humidity_encoder

array([0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0])

In [11]:
from sklearn.preprocessing import LabelEncoder
lab=LabelEncoder()
wind_encoder=lab.fit_transform(wind)
wind_encoder

array([1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0])

In [13]:
#zip
feature=list(zip(outlook_encoder,temperature_encoder,humidity_encoder,wind_encoder))
feature

[(np.int64(2), np.int64(1), np.int64(0), np.int64(1)),
 (np.int64(2), np.int64(1), np.int64(0), np.int64(0)),
 (np.int64(0), np.int64(1), np.int64(0), np.int64(1)),
 (np.int64(1), np.int64(2), np.int64(0), np.int64(1)),
 (np.int64(1), np.int64(0), np.int64(1), np.int64(1)),
 (np.int64(1), np.int64(0), np.int64(1), np.int64(0)),
 (np.int64(0), np.int64(0), np.int64(1), np.int64(0)),
 (np.int64(2), np.int64(2), np.int64(0), np.int64(1)),
 (np.int64(2), np.int64(0), np.int64(1), np.int64(1)),
 (np.int64(1), np.int64(2), np.int64(1), np.int64(1)),
 (np.int64(2), np.int64(2), np.int64(1), np.int64(0)),
 (np.int64(0), np.int64(2), np.int64(0), np.int64(0)),
 (np.int64(0), np.int64(1), np.int64(1), np.int64(1)),
 (np.int64(1), np.int64(2), np.int64(0), np.int64(0))]

In [14]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(feature,decision)
print(model.predict([[2,0,0,0]]))

['No']
